# Generated by Django 6.0.5 on 2026-05-12 00:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroFoco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_foco', models.IntegerField(help_text='Nível de 1 (muito distraído) a 5 (estado de flow)', validators=[django.core.validators.MinValueValidator(1, message='O nível mínimo de foco é 1.'), django.core.validators.MaxValueValidator(5, message='O nível máximo de foco é 5.')], verbose_name='Nível de Foco')),
                ('tempo_minutos', models.PositiveIntegerField(help_text='Quantidade de minutos que durou a sessão de trabalho', verbose_name='Duração (minutos)')),
                ('comentario', models.TextField(help_text='Descreva o que foi feito ou o que causou distração', verbose_name='Comentário')),
                ('categoria', models.CharField(choices=[('coding', 'Programação'), ('reuniao', 'Reunião'), ('estudo', 'Estudo'), ('escrita', 'Escrita/Documentação'), ('revisao', 'Revisão de Código'), ('outro', 'Outro')], default='outro', help_text='Tipo de atividade realizada', max_length=20, verbose_name='Categoria')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Lista de tags para categorizar a sessão. Ex: ["sprint", "bug-fix"]', null=True, verbose_name='Tags')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Registro de Foco',
                'verbose_name_plural': 'Registros de Foco',
                'ordering': ['-data_criacao'],
                'indexes': [models.Index(fields=['data_criacao'], name='idx_data_criacao'), models.Index(fields=['nivel_foco'], name='idx_nivel_foco'), models.Index(fields=['categoria'], name='idx_categoria')],
            },
        ),
    ]
